logit/BC/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fmq.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
     url(r'^$', 'BC.views.index',name='index'),
     url(r'^search/$', 'BC.views.search', name='search'),
     url(r'^profile/(?P<username>\w+)/$', 'BC.views.profile', name='profile'),
     url(r'^logs/$', 'BC.views.circles', name='circles'),
     url(r'^logs/group/create$', 'BC.views.circle_create', name='circle_create'),
     url(r'^logs/(?P<id>\d+)$', 'BC.views.logs', name='logs'),
     url(r'^logs/(?P<id>\d+)/add/$', 'BC.views.new_log', name='add_log'),
     url(r'^logs/(?P<pid>\d+)/detail/(?P<id>\d+)/$', 'BC.views.log_detail', name='log_detail'),
     url(r'^logs/(?P<pid>\d+)/detail/(?P<id>\d+)/add/$', 'BC.views.log_detail_add', name='log_detail_add'),
   )

logit/logit/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('main.urls', namespace="main")), #allowed routes for login, logout, register
    url('', include('BC.urls', namespace="businesscore")),
    url('', include('social.apps.django_app.urls', namespace="social"))
    #url(r'^dashboard/', include('main.urls')), #maps mysite.com/dashboard to everything that is coded in main app
]

logit/main/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fmq.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^login/$', 'main.views.login', name='login'), #maps url to login 
    url(r'^password/reset/$', 'main.views.pass_reset', name='pass_reset'),
    url(r'^signup/$', 'main.views.signup', name='signup'),
    url(r'^logout/$', 'main.views.logout_view', name='logout'),
   )

logit/main/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

####Stores your friends###
class Friendship(models.Model):
    created = models.DateTimeField(auto_now_add=True, editable=False)
    creator = models.ForeignKey(User, related_name="friendship_creator_set")
    friend = models.ForeignKey(User, related_name="friend_set")
    STATUS = (
        ('A', 'ACEPTADO'),
        ('P', 'PENDIENTE'),
        ('N', 'NOAMIGOS'),
    )
    status = models.CharField(max_length=1, choices=STATUS, null=True, default='N')

    def friend_request_sent(self):
        self.status = 'P'
        self.save()

    def friend_request_accepted(self):
        self.status = 'A'
        self.save()

    def unfriend(self):
        self.status = 'N'
        self.save()

    def __unicode__(self):
        return self.friend.username

class Circles(models.Model):
    name = models.CharField(max_length=50, help_text='Name your group!', default=' ')
    description = models.TextField(help_text='Describe your group...', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    group = models.ManyToManyField(Friendship)

    def __unicode__(self):
        return self.name


class Logs(models.Model):
	created = models.DateTimeField(auto_now_add=True, editable=False)
	group = models.ForeignKey(Circles, related_name="log_set")
	description = models.CharField(max_length=100, help_text="This is the grey text")

class tinylog(models.Model):
    log = models.ForeignKey(Logs, related_name="log")
    created = models.DateTimeField(auto_now_add=True, editable=False)
    value = models.DecimalField(max_digits=6, decimal_places=2)
    who = models.CharField(max_length=100)

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
 
    def __unicode__(self):
        return "{}'s profile".format(self.user.username)
 
    class Meta:
        db_table = 'user_profile'
 
    def account_verified(self):
        if self.user.is_authenticated:
            result = EmailAddress.objects.filter(email=self.user.email)
            if len(result):
                return result[0].verified
        return False                               
 
User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

logit/main/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ('username', 'email', 'password', 'first_name', 'last_name')

logit/main/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, logout, login as auth_login
from main.forms import UserForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def login(request):
	#if request.user.is_authenticated():
		#return HttpResponse("yuss")
	if 'login' in request.POST:
		user = authenticate(username=request.POST['username'], password=request.POST['password'])
		if user is not None:
		    # the password verified for the user
		    if user.is_active:
		    	auth_login(request, user)
		        return HttpResponseRedirect('/')
		    else:
		        login_error_code = 2
		else:
		    # the authentication system was unable to verify the username and password
		    login_error_code = 1
	template = 'main/index.html'
	instance = RequestContext(request, locals())
   	return render_to_response(template, context_instance=instance)

def pass_reset(request):
	template = 'main/pass_reset.html'
	instance = RequestContext(request, locals())
	return render_to_response(template, context_instance=instance)

def signup(request):
	if 'submit_register' in request.POST:
		user_form = UserForm(request.POST)
		pass_validator = validation_pass(request.POST['password'], request.POST['rpassword'])
		if user_form.is_valid() and pass_validator:
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			return HttpResponseRedirect('/')
	template = 'main/signup.html'
	instance = RequestContext(request, locals())
	return render_to_response(template, context_instance=instance)

@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/accounts/login/')


def validation_pass(pass1, pass2):
	if pass1 and pass2:
		if pass1 != pass2:
			return False
		else:
			return True
	return False

logit/main/templates/main/basesocialaccount.html
<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.5
Version: 3.3.0
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
<meta charset="utf-8"/>
<title>Metronic | Login Options - Login Form 2</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta content="" name="description"/>
<meta content="" name="author"/>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
<link href="/static/main/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="/static/main/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
<link href="/static/main/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="/static/main/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL STYLES -->
<link href="/static/main/admin/pages/css/login2.css" rel="stylesheet" type="text/css"/>
<!-- END PAGE LEVEL SCRIPTS -->
<!-- BEGIN THEME STYLES -->
<link href="/static/main/global/css/components-rounded.css" id="style_components" rel="stylesheet" type="text/css"/>
<link href="/static/main/global/css/plugins.css" rel="stylesheet" type="text/css"/>
<link href="/static/main/admin/layout/css/layout.css" rel="stylesheet" type="text/css"/>
<link href="/static/main/admin/layout/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
<link href="/static/main/admin/layout/css/custom.css" rel="stylesheet" type="text/css"/>
<!-- END THEME STYLES -->
<link rel="shortcut icon" href="favicon.ico"/>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="login">
<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
<div class="menu-toggler sidebar-toggler">
</div>
<!-- END SIDEBAR TOGGLER BUTTON -->
<!-- BEGIN LOGO -->
<div class="logo">
	<a href="index.html">
	<img src="/static/main/admin/layout4/img/logo-big-white.png" style="height: 17px;" alt=""/>
	</a>
</div>
<!-- END LOGO -->

<!-- BEGIN LOGIN -->
<div class="content">
{% block content %}


<!-- END CONTENT -->
{% endblock %}

</div>

<div class="copyright hide">
	 2014 © Metronic. Admin Dashboard Template.
</div>
<!-- END LOGIN -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="/static/main/global/plugins/respond.min.js"></script>
<script src="/static/main/global/plugins/excanvas.min.js"></script> 
<![endif]-->
<script src="/static/main/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="/static/main/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
<script src="/static/main/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/static/main/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="/static/main/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="/static/main/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="/static/main/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="/static/main/global/scripts/metronic.js" type="text/javascript"></script>
<script src="/static/main/admin/layout/scripts/layout.js" type="text/javascript"></script>
<script src="/static/main/admin/layout/scripts/demo.js" type="text/javascript"></script>
<script src="/static/main/admin/pages/scripts/login.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
jQuery(document).ready(function() {     
Metronic.init(); // init metronic core components
Layout.init(); // init current layout
Login.init();
Demo.init();
});
</script>
<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>

logit/main/templates/main/index.html
{% extends "main/basesocialaccount.html" %}

{% block content %}

	<!-- BEGIN LOGIN FORM -->
	<form class="login-form" action="{% url 'main:login' %}" method="post">
	{% csrf_token %}
		<div class="form-title">
			<span class="form-title">Welcome.</span>
			<span class="form-subtitle">Please login.</span>
		</div>
		<div class="alert alert-danger display-hide">
			<button class="close" data-close="alert"></button>
			<span>
			Enter any username and password. </span>
		</div>
		{% if login_error_code %}
			{% if login_error_code == 1 %}
				The username and password were incorrect.
			{% elif login_error_code == 2 %}
				The account has been disabled!
			{% endif %}
		{% endif %}
		<div class="form-group">
			<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
			<label class="control-label visible-ie8 visible-ie9">Username</label>
			<input class="form-control form-control-solid placeholder-no-fix" type="text" autocomplete="off" placeholder="Username" name="username" required/>
		</div>
		<div class="form-group">
			<label class="control-label visible-ie8 visible-ie9">Password</label>
			<input class="form-control form-control-solid placeholder-no-fix" type="password" autocomplete="off" placeholder="Password" name="password" required/>
		</div>
		<div class="form-actions">
			<button type="submit" class="btn btn-primary btn-block uppercase" name="login">Login</button>
		</div>
		
		<div class="login-options">
			<h4 class="pull-left">Or login with</h4>
			<ul class="social-icons pull-right">
				<li>
					<a class="social-icon-color facebook" data-original-title="facebook" href="{% url 'social:begin' 'facebook' %}"></a>
				</li>
				
			</ul>
		</div>
		<div class="create-account">
			<p>
				<a href="{% url 'main:signup' %}" id="register-btn">Create an account</a>
			</p>
		</div>
	</form>

{% endblock %}

logit/main/templates/main/pass_reset.html
{% extends "main/basesocialaccount.html" %}

{% block content %}
<!-- BEGIN FORGOT PASSWORD FORM -->
<form class="login-form" action="index.html" method="post">


	<div class="form-title">
		<span class="form-title">Forget Password ?</span>
		<span class="form-subtitle">Enter your e-mail to reset it.</span>
	</div>
	<div class="form-group">
		<input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Email" name="email"/>
	</div>
	<div class="form-actions">
		<button type="button" onclick="location.href = '{% url 'main:login' %} ';" id="back-btn" class="btn btn-default">Back</button>
		<button type="submit" class="btn btn-primary uppercase pull-right">Submit</button>
	</div>
</form>
	<!-- END FORGOT PASSWORD FORM -->
{% endblock %}

logit/main/templates/main/signup.html
{% extends "main/basesocialaccount.html" %}

{% block content %}	

	<!-- BEGIN REGISTRATION FORM -->
	<form class="login-form" action="{% url 'main:signup' %}" method="post">
	{% csrf_token %}
		<div class="form-title">
			<span class="form-title">Sign Up</span>
		</div>	
		<p class="hint">
			 Enter your personal details below:
		</p>
		{{ user_form.non_field_errors }}
		<div class="form-group">
			{{ user_form.first_name.errors }}
			<label class="control-label visible-ie8 visible-ie9">First Name</label>
			<input class="form-control placeholder-no-fix" type="text" placeholder="First Name" name="first_name" value="{{user_form.first_name.value|default_if_none:''}}" required/>
		</div>
		<div class="form-group">
			{{ user_form.last_name.errors }}
			<label class="control-label visible-ie8 visible-ie9">Last Name</label>
			<input class="form-control placeholder-no-fix" type="text" placeholder="Last Name" name="last_name" value="{{user_form.last_name.value|default_if_none:''}}" required/>
		</div>
		<div class="form-group">
			<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
			{{ user_form.email.errors }}
			<label class="control-label visible-ie8 visible-ie9">Email</label>
			<input class="form-control placeholder-no-fix" type="text" placeholder="Email" name="email" value="{{user_form.email.value|default_if_none:''}}" required/>
		</div>
		
		<p class="hint">
			 Enter your account details below:
		</p>
		<div class="form-group">
			{{ user_form.username.errors }}
			<label class="control-label visible-ie8 visible-ie9">Username</label>
			<input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Username" name="username" value="{{user_form.username.value|default_if_none:''}}" required/>
		</div>
		<div class="form-group">
			{% if not pass_validator %}
				Pass do not match
			{% endif %}
			<label class="control-label visible-ie8 visible-ie9">Password</label>
			<input class="form-control placeholder-no-fix" type="password" autocomplete="off" id="register_password" placeholder="Password" name="password" required/>
		</div>
		<div class="form-group">
			<label class="control-label visible-ie8 visible-ie9">Re-type Your Password</label>
			<input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Re-type Your Password" name="rpassword" required/>
		</div>
		<div class="form-actions">
			<button type="button" onclick="location.href = '{% url 'main:login' %} ';" id="register-back-btn" class="btn btn-default">Back</button>
			<button type="submit" id="register-submit-btn" class="btn btn-primary uppercase pull-right" name="submit_register">Submit</button>
		</div>
	</form>
	<!-- END REGISTRATION FORM -->

{% endblock %}